# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [8]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7,7))
print(random_tensor, random_tensor.size(), random_tensor.dim())


tensor([[0.2286, 0.3992, 0.9255, 0.0925, 0.4227, 0.1799, 0.9420],
        [0.0169, 0.8321, 0.6205, 0.0443, 0.6813, 0.8284, 0.9329],
        [0.7993, 0.3494, 0.0434, 0.6255, 0.6556, 0.7601, 0.6161],
        [0.1676, 0.7797, 0.9682, 0.1494, 0.3159, 0.6412, 0.9282],
        [0.4688, 0.8202, 0.5934, 0.3769, 0.2550, 0.3587, 0.4989],
        [0.4807, 0.4124, 0.7132, 0.9060, 0.7351, 0.2365, 0.5829],
        [0.8912, 0.2759, 0.7478, 0.7605, 0.8474, 0.2798, 0.6021]]) torch.Size([7, 7]) 2


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
another_random_tensor = torch.rand(size=(1,7))
# Perform matrix multiplication 
mult_matrix = torch.mm(random_tensor, another_random_tensor.T)
print(mult_matrix, mult_matrix.size())

tensor([[1.5385],
        [2.1548],
        [1.9974],
        [1.8933],
        [1.3650],
        [1.8200],
        [1.8754]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [25]:
# Set manual seed
SEED = 0
torch.manual_seed(SEED)
# Create two random tensors
new_tensor = torch.rand(size=(7,7))
new_another_tensor = torch.rand(size=(1,7))

# Matrix multiply tensors

new_mult = torch.mm(new_tensor,new_another_tensor.T)
print(new_mult, new_mult.size())


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [31]:
# Set random seed on the GPU
seed = 0
torch.cuda.random.manual_seed(seed)

# Create two random tensors
new_tensor_gpu = torch.rand(size=(7,7),device="cuda")
new_another_tensor_gpu = torch.rand(size=(1,7),device="cuda")

# Matrix multiply tensors

new_mul_gpu = torch.mm(new_tensor_gpu,new_another_tensor_gpu.T)
print(new_mul_gpu, new_mul_gpu.size())


tensor([[2.0534],
        [2.3578],
        [1.8793],
        [1.6912],
        [2.5042],
        [2.0659],
        [1.9022]], device='cuda:0') torch.Size([7, 1])



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
rs = 42
torch.cuda.random.manual_seed(rs)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor1 = torch.rand(size=(2,3),device=device)
tensor2 = torch.rand(size=(2,3),device=device)

print(f'Device: {device}')
print(tensor1)
print(tensor2)


Device: cuda
tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')
tensor([[0.9877, 0.1289, 0.5621],
        [0.5221, 0.7445, 0.5955]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [36]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor1,tensor2.T)
result, result.size()

(tensor([[0.8307, 0.5648],
         [0.3312, 0.4247]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [41]:
# Find max
maximum = torch.max(result)
# Find min
minimum = torch.min(result)

minimum,maximum

(tensor(0.3312, device='cuda:0'), tensor(0.8307, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [43]:
# Find arg max
index_max = torch.argmax(result)

# Find arg min
index_min = torch.argmin(result)
index_min, index_max


(tensor(2, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [47]:
# Set seed
seed = 7

# Create random tensor
tensor_new = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_squeezed = torch.squeeze(tensor_new)

# Print out tensors and their shapes
print(tensor_new, tensor_new.size())
print(tensor_squeezed, tensor_squeezed.size())

tensor([[[[0.2032, 0.3151, 0.0044, 0.7257, 0.2599, 0.1663, 0.2119, 0.7875,
           0.7648, 0.8838]]]]) torch.Size([1, 1, 1, 10])
tensor([0.2032, 0.3151, 0.0044, 0.7257, 0.2599, 0.1663, 0.2119, 0.7875, 0.7648,
        0.8838]) torch.Size([10])
